export const APP_ROLE = {
  SUPERADMIN: 'superadmin',
  ENTITY_ADMIN: 'entity_admin',
  ENTITY: 'entity',
  BRAND_ADMIN: 'brand_admin',
  BRAND_BRANCH_ADMIN: 'brand_branch_admin',
  BRANCH_ADMIN: 'branch_admin',
  DEALER_ADMIN: 'dealer_admin',
  SALES_ADMIN: 'sales_admin',
  SALES_PERSON: 'sales_person',
  GRO: 'gro',
  SALES: 'sales',
  SECURITY: 'security',
} as const;

export type AppRole = (typeof APP_ROLE)[keyof typeof APP_ROLE];
export type CanonicalAppRole =
  | typeof APP_ROLE.SUPERADMIN
  | typeof APP_ROLE.DEALER_ADMIN
  | typeof APP_ROLE.SALES_ADMIN
  | typeof APP_ROLE.SALES_PERSON
  | typeof APP_ROLE.GRO
  | typeof APP_ROLE.SECURITY;

export const APP_ROLE_VALUES: AppRole[] = Object.values(APP_ROLE);
export const DEFAULT_APP_ROLE: CanonicalAppRole = APP_ROLE.SALES_PERSON;

export const CANONICAL_APP_ROLE_VALUES: CanonicalAppRole[] = [
  APP_ROLE.SUPERADMIN,
  APP_ROLE.DEALER_ADMIN,
  APP_ROLE.SALES_ADMIN,
  APP_ROLE.SALES_PERSON,
  APP_ROLE.GRO,
  APP_ROLE.SECURITY,
];

export const LEGACY_ROLE_ALIASES: Partial<Record<AppRole, CanonicalAppRole>> = {
  [APP_ROLE.ENTITY_ADMIN]: APP_ROLE.DEALER_ADMIN,
  [APP_ROLE.ENTITY]: APP_ROLE.DEALER_ADMIN,
  [APP_ROLE.BRAND_ADMIN]: APP_ROLE.DEALER_ADMIN,
  [APP_ROLE.BRAND_BRANCH_ADMIN]: APP_ROLE.SALES_ADMIN,
  [APP_ROLE.BRANCH_ADMIN]: APP_ROLE.SALES_ADMIN,
  [APP_ROLE.SALES]: APP_ROLE.SALES_PERSON,
};

export const APP_ROLE_LABELS: Record<AppRole, string> = {
  [APP_ROLE.SUPERADMIN]: 'Super Admin',
  [APP_ROLE.ENTITY_ADMIN]: 'Entity Admin',
  [APP_ROLE.ENTITY]: 'Entity',
  [APP_ROLE.BRAND_ADMIN]: 'Brand Admin',
  [APP_ROLE.BRAND_BRANCH_ADMIN]: 'Brand Branch Admin',
  [APP_ROLE.BRANCH_ADMIN]: 'Branch Admin',
  [APP_ROLE.DEALER_ADMIN]: 'Dealer Admin',
  [APP_ROLE.SALES_ADMIN]: 'Sales Admin',
  [APP_ROLE.GRO]: 'GRO',
  [APP_ROLE.SALES_PERSON]: 'Sales Person',
  [APP_ROLE.SALES]: 'Sales',
  [APP_ROLE.SECURITY]: 'Security',
};

export const APP_ROLE_BADGE_CLASS: Record<AppRole, string> = {
  [APP_ROLE.SUPERADMIN]: 'bg-destructive/10 text-destructive',
  [APP_ROLE.ENTITY_ADMIN]: 'bg-red-100 text-red-700',
  [APP_ROLE.ENTITY]: 'bg-destructive/10 text-destructive',
  [APP_ROLE.BRAND_ADMIN]: 'bg-emerald-100 text-emerald-700',
  [APP_ROLE.BRAND_BRANCH_ADMIN]: 'bg-emerald-50 text-emerald-700',
  [APP_ROLE.BRANCH_ADMIN]: 'bg-purple-100 text-purple-700',
  [APP_ROLE.DEALER_ADMIN]: 'bg-secondary/10 text-secondary-foreground',
  [APP_ROLE.SALES_ADMIN]: 'bg-orange-100 text-orange-700',
  [APP_ROLE.GRO]: 'bg-primary/10 text-primary',
  [APP_ROLE.SALES_PERSON]: 'bg-info/10 text-info',
  [APP_ROLE.SALES]: 'bg-info/20 text-info',
  [APP_ROLE.SECURITY]: 'bg-warning/10 text-warning',
};

export const STAFF_ROLE_OPTIONS = [
  { value: APP_ROLE.DEALER_ADMIN, label: 'Dealer Admin' },
  { value: APP_ROLE.SALES_ADMIN, label: 'Sales Admin' },
  { value: APP_ROLE.GRO, label: 'GRO' },
  { value: APP_ROLE.SALES_PERSON, label: 'Sales Person' },
  { value: APP_ROLE.SECURITY, label: 'Security' },
] as const;

// Roles that Dealer Admin can assign (cannot assign Superadmin)
export const DEALER_ASSIGNABLE_ROLES = [
  { value: APP_ROLE.SALES_ADMIN, label: 'Sales Admin' },
  { value: APP_ROLE.GRO, label: 'GRO' },
  { value: APP_ROLE.SALES_PERSON, label: 'Sales Person' },
  { value: APP_ROLE.SECURITY, label: 'Security' },
] as const;

export const ROUTE_ALLOWED_ROLES = {
  WALKIN: [APP_ROLE.GRO, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.SALES_PERSON],
  ENQUIRIES: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.GRO, APP_ROLE.SALES_PERSON],
  BOOKINGS: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.GRO, APP_ROLE.SALES_PERSON],
  HIERARCHY: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN],
  LOCATIONS: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN],
  VEHICLES: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.GRO, APP_ROLE.SALES_PERSON],
  USERS: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN],
  DATA_CENTER: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN],
  SETTINGS: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN],
  REPORTS_MONITORING: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.SALES_PERSON],
  ACTIVITY_LOGS: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.GRO, APP_ROLE.SECURITY, APP_ROLE.SALES_PERSON],
  FLEET: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.SECURITY, APP_ROLE.SALES_PERSON],
  INCOMING_VEHICLES: [APP_ROLE.SUPERADMIN, APP_ROLE.DEALER_ADMIN, APP_ROLE.SALES_ADMIN, APP_ROLE.SECURITY, APP_ROLE.GRO, APP_ROLE.SALES_PERSON],
} as const;